### PR TITLE
Transmission revision

### PR DESCRIPTION
**Pull request by ercrema**
This commits include the new version of decisionMaking.R which should include both the fix for the 'else' problem, as well as the bug with the sample() function that was generated when the agent was surrounded by empty cells.

### CODE REVIEW

**Comment by ercrema** [comment]
I think the best is to accept just decisionMaking.R in case it is working?

**Comment by ercrema** [comment]
So all good?

**Comment by ercrema** [comment]
There is also an issue with the parameter names, I think there were two different versions circulating. We probably need to check this throughout all the codes once we agreed how to proceed forward

**Comment by xrubio** [comment]
Yep, I already pushed the request! About parameter names I need to check my code because I suspect that I changed slightly some of them...

**Pull request merged**
